spec: fix check for castxml on CentOS 7 aarch64 platform (#1162)
The BuildRequires check for castxml on CentOS 7 aarch64
platform is not working well, it still requires castxml
package to be present:

    error: Failed build dependencies:
          castxml is needed by cortx-motr...

But the check should be skipped because castxml rpm is not
available on CentOS 7.

Solution: fix `%if` directive which does the check, avoid
using `%if else`.

Signed-off-by: Andriy Tkachuk <andriy.tkachuk@seagate.com>
(cherry picked from commit 81068af0440905b67a010ae63cbfebb99a2b0a60)